### ISSUE TITLE
Shindo should be replaced with minitest

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog-google#50]
Per fog/fog#1266 and fog/fog#2630, Minitest is the new testing framework to be used by fog projects.
- [x] #51 is open to cover `compute` in integration tests.
- [ ] Nothing is unit-tested with `minitest`; it should be.  Opening #49.
- [ ] Furthermore, it's not clear whether or not we can run these integration tests in Travis CI, (see #19).  Regardless, unit tests should be run in Travis.
- [ ] #51 only covers `compute`.  `dns`, `monitoring`, `sql`, and `storage` all remain tested in under shindo, and should be moved over to `minitest`.
- [x] The Rakefile is kind of a mess, and should eventually be cleaned up.

**Comment by icco** [comment]
Sub issues have mostly been closed.
